# Generated by Django 4.0.3 on 2022-04-08 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbcs', '0003_remove_course_course_staff_course_course_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=10)),
                ('course_name', models.CharField(max_length=70)),
                ('course_staff', models.ManyToManyField(to='cbcs.teacher')),
            ],
        ),
        migrations.DeleteModel(
            name='Course',
        ),
    ]
