# Generated by Django 4.0.3 on 2022-04-08 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cbcs', '0004_courses_delete_course'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Courses',
            new_name='Course',
        ),
    ]
